const getList =(author,keyword)=>{
    return[
        {
            id:1,
            title:'标题1',
            content:'内容1',
            createTime:'1546610491112',
            author:'张三',
        },
        {
            id:2,
            title:'标题2',
            content:'内容3',
            createTime:'1546610445823',
            author:'李四',
        }
    ]
}
module.exports={
    getList
}